In [2]:
import numpy as np

In [4]:
#Oppg1
def ivm(a, b):
    return (a+b)/2

def halvering_solve(f, a,b, tol):
    c = ivm(a,b)
    if abs(a-b) < tol:
        print("c: " + str(c))
        return a, b, c

    if f(a) * f(c) < 0:
        return halvering_solve(f,a, c, tol)
    if f(b) * f(c) < 0:
        return halvering_solve(f,c, b, tol)

a = 1
b = 3
f = lambda x: x**3-9#Hvilken funksjon f er det du skal finne roten av?
maks_feil = 1.0*10**(-6)#Hva blir maks feil om x_sol skal være riktig med minst 6 desimaler?
x_sol = halvering_solve(f,a,b, maks_feil) #Hva må startintervallet være?
print(x_sol)

c: 2.0800833702087402
(2.080082893371582, 2.0800838470458984, 2.0800833702087402)


In [53]:
#Oppg 2
def fikspunkt_solve(f, x0,tol):

   while (abs(f(x0)-x0) > tol):
       x0 = f(x0)

   return x0

f1 = lambda x: x**3-2*x-2
f2 = lambda x: np.exp(x) + 2*x - 7
f3 = lambda x: np.exp(x) + np.sin(x) - 4 - x
funcs = [f1,f2,f3]
maks_feil = 1.0*10**(-8)
sols = []
for f in funcs:
   x_sol = fikspunkt_solve(f, 1, maks_feil)
   print(x_sol)
   sols.append(x_sol)

print(f"Løsning til første ligning x = {sols[0]}")
print(f"Løsning til andre ligning x = {sols[1]}")
print(f"Løsning til tredje ligning x = {sols[2]}")

KeyboardInterrupt: 

In [8]:
#Oppg6
def r(V, h, r):
    return np.pi*r**2*h/3+4/3*np.pi*r**3/2 - V

def rd(r, h):
    return np.pi*2*r*h/3 + 3*4/3*np.pi*r**2/2


def newtons_method(x0, h, V, err):
    x1 = x0 - r(V,h,x0)/rd(x0,h)
    while abs(x1 - x0) > err:
        x0 = x1
        x1 = x0 - r(V,h,x0)/rd(x0,h)

    return x1
#---------> Kod i vei


#<--------------
h = 10
V = 60
x0 = 1
err = 1.0*10**(-4)
radius = newtons_method(x0,h,V, err)
print(radius)

2.0201073212543124


In [124]:
#Oppg9
def naive_gauss(A,b):
   n,m = np.shape(A)
   S = np.zeros((n,n+1))
   S[:,0:n] = A
   S[:,-1] = b
   for j in range(n-1):
      for i in range(j+1,n):
         mult = S[i,j]/S[j,j]

         for k in range(j+1,n):
            S[i,k] = S[i,k] - mult*S[j,k]
         S[i,-1] = S[i,-1] - mult*S[j,-1]
         S[i,j]=0.0
   return S[:,0:n],S[:,-1]
#Forslag til fremgangsmåte til definere A, b
#-Viser noen nyttige np-funksjoner
A = np.array([ 1,2,-1,0,3,1,2,-1,1])
A=A.reshape((3,3))
b = np.array([2,4,2]).T
Ar, br = naive_gauss(A,b)
print(Ar)
print(br)

[[ 1.          2.         -1.        ]
 [ 0.          3.          1.        ]
 [ 0.          0.          4.66666667]]
[2.         4.         4.66666667]


In [145]:
#Oppg10
def naive_gauss(A,b):
   n,m = np.shape(A)
   S = np.zeros((n,n+1))
   S[:,0:n] = A
   S[:,-1] = b
   for j in range(n-1):
      for i in range(j+1,n):
         mult = S[i,j]/S[j,j]
         S[i,j]=0.0
         for k in range(j+1,n):
            S[i,k] = S[i,k] - mult*S[j,k]
         S[i,-1] = S[i,-1] - mult*S[j,-1]
   x = S[:,-1]

   for i in range(n-1, -1, -1):
      for j in range(n-1,i,-1):
         S[i, i] = S[i,i] + S[i, j]*x[j]
      x[i] = S[i,-1]/S[i, i]
   return x

A = np.array([ 1,2,-1,0,3,1,2,-1,1])
A=A.reshape((3,3))
b = np.array([2,4,2]).T
x= naive_gauss(A,b)
print(x)

[1. 1. 1.]


In [137]:
import math


#Oppgave 11

def naive_gauss(A,b):
   n,m = np.shape(A)
   S = np.zeros((n,m+1))
   S[:,0:n] = A
   S[:,-1] = b
   for j in range(n-1):
      for i in range(j+1,n):
         mult = S[i,j]/S[j,j]
         S[i,j]=0.0
         for k in range(j+1,n):
            S[i,k] = S[i,k] - mult*S[j,k]
         S[i,-1] = S[i,-1] - mult*S[j,-1]
   x = S[:,-1]
   for i in range(n-1, -1, -1):
      for j in range(n-1,i,-1):
         S[i, i] = S[i,i] - S[i, j]*x[j]
      x[i] = S[i,-1]/S[i, i]
   return x


ns = [2,5,10]
xs = []
for n in ns:
    H = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            H[i,j] = 1/((i+1)+(j+1)-1)
    b = np.ones((1,n))
    #<-------------
    #print(H)
    x = naive_gauss(H,b)
    xs.append(x)
    bakoverfeil = (np.max(np.abs(np.dot(H,x)-b))) #Om du var nysgjerrig :)
print(xs[0])

[-0.5  6. ]
